### ISSUE TITLE
np.int causing DeprecationWarning

### ISSUE THREAD

**Issue by igrodger** [SebastianHoerning/RMWSPy#7]
Looks like this can simply be changed to int?

fftma.py:42: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.      
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by SebastianHoerning** [comment]
Yes, I think that can just be changed. Just give it go and push if it works.

**Comment by igrodger** [comment]
I've repleaced np.int with int in the fftma, specsim, and  random mixing scripts and pushed.
